<?php

namespace Proxies\__CG__\PadelSchedule\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Inscripcion extends \PadelSchedule\MainBundle\Entity\Inscripcion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'id', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'jugador', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'competicion', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'nombrePareja', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'partidosGanados', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'partidosPerdidos', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'partidosEmpatados', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioLunes', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioMartes', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioMiercoles', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioJueves', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioViernes', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioSabado', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioDomingo'];
        }

        return ['__isInitialized__', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'id', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'jugador', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'competicion', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'nombrePareja', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'partidosGanados', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'partidosPerdidos', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'partidosEmpatados', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioLunes', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioMartes', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioMiercoles', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioJueves', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioViernes', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioSabado', '' . "\0" . 'PadelSchedule\\MainBundle\\Entity\\Inscripcion' . "\0" . 'horarioDomingo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Inscripcion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setJugador(\PadelSchedule\UserBundle\Entity\User $jugador = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJugador', [$jugador]);

        return parent::setJugador($jugador);
    }

    /**
     * {@inheritDoc}
     */
    public function getJugador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJugador', []);

        return parent::getJugador();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompeticion(\PadelSchedule\MainBundle\Entity\Competicion $competicion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompeticion', [$competicion]);

        return parent::setCompeticion($competicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompeticion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompeticion', []);

        return parent::getCompeticion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombrePareja($nombrePareja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombrePareja', [$nombrePareja]);

        return parent::setNombrePareja($nombrePareja);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombrePareja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombrePareja', []);

        return parent::getNombrePareja();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuntos($puntos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuntos', [$puntos]);

        return parent::setPuntos($puntos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntos', []);

        return parent::getPuntos();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferenciaLunes($preferenciaLunes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferenciaLunes', [$preferenciaLunes]);

        return parent::setPreferenciaLunes($preferenciaLunes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferenciaLunes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferenciaLunes', []);

        return parent::getPreferenciaLunes();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferenciaMartes($preferenciaMartes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferenciaMartes', [$preferenciaMartes]);

        return parent::setPreferenciaMartes($preferenciaMartes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferenciaMartes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferenciaMartes', []);

        return parent::getPreferenciaMartes();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferenciaMiercoles($preferenciaMiercoles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferenciaMiercoles', [$preferenciaMiercoles]);

        return parent::setPreferenciaMiercoles($preferenciaMiercoles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferenciaMiercoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferenciaMiercoles', []);

        return parent::getPreferenciaMiercoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferenciaJueves($preferenciaJueves)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferenciaJueves', [$preferenciaJueves]);

        return parent::setPreferenciaJueves($preferenciaJueves);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferenciaJueves()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferenciaJueves', []);

        return parent::getPreferenciaJueves();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferenciaViernes($preferenciaViernes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferenciaViernes', [$preferenciaViernes]);

        return parent::setPreferenciaViernes($preferenciaViernes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferenciaViernes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferenciaViernes', []);

        return parent::getPreferenciaViernes();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferenciaSabado($preferenciaSabado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferenciaSabado', [$preferenciaSabado]);

        return parent::setPreferenciaSabado($preferenciaSabado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferenciaSabado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferenciaSabado', []);

        return parent::getPreferenciaSabado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferenciaDomingo($preferenciaDomingo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferenciaDomingo', [$preferenciaDomingo]);

        return parent::setPreferenciaDomingo($preferenciaDomingo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferenciaDomingo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferenciaDomingo', []);

        return parent::getPreferenciaDomingo();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioLunes($horarioLunes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioLunes', [$horarioLunes]);

        return parent::setHorarioLunes($horarioLunes);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioLunes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioLunes', []);

        return parent::getHorarioLunes();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioMartes($horarioMartes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioMartes', [$horarioMartes]);

        return parent::setHorarioMartes($horarioMartes);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioMartes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioMartes', []);

        return parent::getHorarioMartes();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioMiercoles($horarioMiercoles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioMiercoles', [$horarioMiercoles]);

        return parent::setHorarioMiercoles($horarioMiercoles);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioMiercoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioMiercoles', []);

        return parent::getHorarioMiercoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioJueves($horarioJueves)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioJueves', [$horarioJueves]);

        return parent::setHorarioJueves($horarioJueves);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioJueves()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioJueves', []);

        return parent::getHorarioJueves();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioViernes($horarioViernes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioViernes', [$horarioViernes]);

        return parent::setHorarioViernes($horarioViernes);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioViernes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioViernes', []);

        return parent::getHorarioViernes();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioSabado($horarioSabado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioSabado', [$horarioSabado]);

        return parent::setHorarioSabado($horarioSabado);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioSabado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioSabado', []);

        return parent::getHorarioSabado();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioDomingo($horarioDomingo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioDomingo', [$horarioDomingo]);

        return parent::setHorarioDomingo($horarioDomingo);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioDomingo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioDomingo', []);

        return parent::getHorarioDomingo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartidosGanados($partidosGanados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartidosGanados', [$partidosGanados]);

        return parent::setPartidosGanados($partidosGanados);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartidosGanados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartidosGanados', []);

        return parent::getPartidosGanados();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartidosPerdidos($partidosPerdidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartidosPerdidos', [$partidosPerdidos]);

        return parent::setPartidosPerdidos($partidosPerdidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartidosPerdidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartidosPerdidos', []);

        return parent::getPartidosPerdidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartidosEmpatados($partidosEmpatados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartidosEmpatados', [$partidosEmpatados]);

        return parent::setPartidosEmpatados($partidosEmpatados);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartidosEmpatados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartidosEmpatados', []);

        return parent::getPartidosEmpatados();
    }

}
